<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
if (!function_exists('getOptionAttribute')) {
    function getOptionAttribute($_product, $attrCode) {
      $optionText = null;
      if ($_product AND $attrCode) {
          $om = \Magento\Framework\App\ObjectManager::getInstance();
          $productRepos = $om->get('\Magento\Catalog\Model\ProductRepository')->getById($_product->getId());
          $optionId = $productRepos->getData($attrCode);
          if ($optionId) {
            $attr = $_product->getResource()->getAttribute($attrCode);
            if ($attr->usesSource()) {
              $optionText = $attr->getSource()->getOptionText($optionId);
            }
          }
      }
      return $optionText;
    }
}
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <?php if ($block->getMode() == 'grid') : ?>

    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products grid items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <div class="item-photo">
                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml(); ?>
                        </a>
                    </div>
                    <div class="product details product-item-details">
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                <a href="#"
                                   class="action towishlist"
                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                   data-action="add-to-wishlist"
                                   role="button">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                </a>
                            <?php endif; ?>
                            <?php if ($_product->isSaleable()): ?>
                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                    <?php echo $block->getBlockHtml('formkey')?>
                                    <button type="submit"
                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                            class="action tocart primary">
                                        <span><?php echo $block->escapeHtml(__('Add to Cart')); ?></span>
                                    </button>
                                </form>
                            <?php else: ?>
                                <?php if ($_product->getIsSalable()): ?>
                                    <div class="stock available"><span><?php echo $block->escapeHtml(__('In Stock')); ?></span></div>
                                <?php else: ?>
                                    <div class="stock unavailable"><span><?php echo $block->escapeHtml(__('Out of Stock')); ?></span></div>
                                <?php endif; ?>
                            <?php endif; ?>
                            
                            <?php
                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                            ?>
                            <a href="#"
                               class="action tocompare"
                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                               role="button">
                                <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                            </a>
                        </div>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php else: ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <div class="item-photo">
                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml(); ?>
                        </a>
                    </div>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php if (getOptionAttribute($_product, 'ub_author')): ?>
                            <div class="ub-author"><?php echo getOptionAttribute($_product, 'ub_author'); ?></div>
                        <?php endif; ?>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                        <div class="product-item-inner">
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                </div>
                            <?php endif; ?>
                            
                        </div>
                        <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                            <?php if ($_product->isSaleable()): ?>
                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                    <?php echo $block->getBlockHtml('formkey')?>
                                    <button type="submit"
                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                            class="action tocart primary">
                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                    </button>
                                </form>
                            <?php else: ?>
                                <?php if ($_product->getIsSalable()): ?>
                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In Stock') ?></span></div>
                                <?php else: ?>
                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of Stock') ?></span></div>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                <a href="#"
                                   class="action towishlist"
                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                   data-action="add-to-wishlist"
                                   role="button">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                </a>
                            <?php endif; ?>
                            <?php
                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                            ?>
                            <a href="#"
                               class="action tocompare"
                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                               role="button">
                                <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                            </a>
                        </div>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php endif; ?>
    <div class="toolbar-bottom">
    <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
